
export const FETCH_TEST_STATE = 'FETCH_TEST_STATE';
export const SET_MOVIES_LOADING = 'SET_MOVIES_LOADING';
export const SET_MOVIES_DATA = 'SET_MOVIES_DATA';
export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR';