export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
