export const FETCH_MOVIES_DATA = 'FETCH_MOVIES_DATA';
export const SET_MOVIES_LOADING = 'SET_MOVIES_LOADING';
export const SET_MOVIES_DATA = 'SET_MOVIES_DATA';
export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR';
